# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main



resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: nn-self
    steps:

    - task: Docker@2
      inputs:
        containerRegistry: 'docker'
        repository: 'narian318/scenery'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'